---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-pvc
  namespace: kserve-nim-playground-knative-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
