apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-pvc
spec:
#  storageClassName: ocs-storagecluster-cephfs
  storageClassName: gp3-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
